### ISSUE TITLE
question about weights

### ISSUE THREAD

**Issue by earthjasonlin** [Zhaokugua/Grasscutter_Banners#4]
Are the weights from official or what?

**Comment by Zhaokugua** [comment]
正常情况下权重应该是和官服一样的
也可以修改json文件里的字段来达到修改权重的效果。
```json
  "weights4":[[1,510],[8,510],[10,10000]],
  "weights5":[[1,80],[73,80],[90,10000]],
```
比如五星的权重，这个表示1-73抽中每一抽你都有0.8%的概率抽到五星角色，73-90抽概率从0.8%逐渐上升到100%，直到你抽出来了五星角色为止。

但是卡池配置文件里有一个叫做`fallbackItemsPool`的东西（似乎是如果歪了从这里面随机选一个歪给你），我不知道怎么正确的修改这东西（主要感觉太麻烦了qwq，如果每次都改的话每加一个新四星他下个版本就会加入常驻也就是能歪出来），这意味着如果你歪了，虽然四星或者五星没错但是可能歪到的角色或者武器不是正常情况下应该歪到的角色或武器。

不过好像这个字段删掉也能用，如果对这方面有需求的话可以试着自己改一改或者直接删掉*

此外还有个`poolBalanceWeights`是控制保底up的角色的，比如四星20连必出一个up，五星180连（大保底）必出up，那个也是默认的和官服一样的。

---

The weights is the same as offical normally.
You can change the weights whatever you want.
```json
  "weights4":[[1,510],[8,510],[10,10000]],
  "weights5":[[1,80],[73,80],[90,10000]],
```
For example, this five star weights means you have 0.8% chance to get a five star in pull No.1 - No.73 each pull.
From No.73, the rate will gradually increase to 100% until you get a five star.

However, there's something called `fallbackItemsPool` which I have no idea how to edit.
That means when you lose a 50/50, the star is correct but the charactor or weapon may be wrong.
I think you can simplely delete the line with "fallbackItemsPool" since it does't matter.

**Comment by earthjasonlin** [comment]
ok，谢谢了
